name: Copy Files

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run copy script
        env:
          SOURCE_REPO_URL: https://github.com/QuietHellsPage/Parent_repo_mirror.git
          TARGET_REPO_URL: https://github.com/QuietHellsPage/Child_repo_mirror.git
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
          JSON_PATH: autosync/test_files.json
        run: |
          python autosync/copy_script.py
